package com.markkryzh.hotel_software_tool.model;
// Generated 28 лист. 2016 23:15:44 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * RoomBooking generated by hbm2java
 */
public class RoomBooking implements java.io.Serializable {

	private int id;
	private Room room;
	private User user;
	private Date fromDate;
	private Date toDate;
	private double price;

	public RoomBooking() {
	}

	public RoomBooking(int id, Room room, User user, Date fromDate, Date toDate, double price) {
		this.id = id;
		this.room = room;
		this.user = user;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
