package com.markkryzh.hotel_software_tool.model;
// Generated 25 лист. 2016 3:50:37 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * RoomType generated by hbm2java
 */
public class RoomType implements java.io.Serializable {

	private int id;
	private String name;
	private Set rooms = new HashSet(0);

	public RoomType() {
	}

	public RoomType(int id, String name) {
		this.id = id;
		this.name = name;
	}

	public RoomType(int id, String name, Set rooms) {
		this.id = id;
		this.name = name;
		this.rooms = rooms;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getRooms() {
		return this.rooms;
	}

	public void setRooms(Set rooms) {
		this.rooms = rooms;
	}

}
