package com.markkryzh.hotel_software_tool.model;
// Generated 25 лист. 2016 3:50:37 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Room generated by hbm2java
 */
public class Room implements java.io.Serializable {

	private Integer id;
	private RoomType roomType;
	private String roomTypeName;
	private Integer capacity;
	private String number;
	private double price;
	private String image;
	private Set roomBookings = new HashSet(0);

	public Room() {
	}

	public Room(Integer id, RoomType roomType, Integer capacity, String number, double price) {
		this.id = id;
		this.roomType = roomType;
		this.capacity = capacity;
		this.number = number;
		this.price = price;
	}

	public Room(Integer id, RoomType roomType, Integer capacity, String number, double price, String image,
			Set roomBookings) {
		this.id = id;
		this.roomType = roomType;
		this.capacity = capacity;
		this.number = number;
		this.price = price;
		this.image = image;
		this.roomBookings = roomBookings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public RoomType getRoomType() {
		return this.roomType;
	}

	public void setRoomType(RoomType roomType) {
		this.roomType = roomType;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getRoomBookings() {
		return this.roomBookings;
	}

	public void setRoomBookings(Set roomBookings) {
		this.roomBookings = roomBookings;
	}

	public String getRoomTypeName() {
		return roomTypeName;
	}

	public void setRoomTypeName(String roomTypeName) {
		this.roomTypeName = roomTypeName;
	}

}
