package com.markkryzh.hotel_software_tool.model;
// Generated 25 лист. 2016 3:50:37 by Hibernate Tools 5.2.0.Beta1

import java.util.Date;

/**
 * RoomBooking generated by hbm2java
 */
public class RoomBooking implements java.io.Serializable {

	private int id;
	private Room room;
	private User user;
	private Date from;
	private Date to;
	private double price;

	public RoomBooking() {
	}

	public RoomBooking(int id, Room room, User user, Date from, Date to, double price) {
		this.id = id;
		this.room = room;
		this.user = user;
		this.from = from;
		this.to = to;
		this.price = price;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Room getRoom() {
		return this.room;
	}

	public void setRoom(Room room) {
		this.room = room;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getFrom() {
		return this.from;
	}

	public void setFrom(Date from) {
		this.from = from;
	}

	public Date getTo() {
		return this.to;
	}

	public void setTo(Date to) {
		this.to = to;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

}
