package com.markkryzh.hotel_software_tool.model;
// Generated 25 лист. 2016 3:50:37 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private Integer id;
	private String description;
	private Integer capacity;
	private String name;
	private double price;
	private String image;
	private Set serviceBookings = new HashSet(0);

	public Service() {
	}

	public Service(Integer id, Integer capacity, String name, double price) {
		this.id = id;
		this.capacity = capacity;
		this.name = name;
		this.price = price;
	}

	public Service(Integer id, String description, Integer capacity, String name, double price, String image,
			Set serviceBookings) {
		this.id = id;
		this.description = description;
		this.capacity = capacity;
		this.name = name;
		this.price = price;
		this.image = image;
		this.serviceBookings = serviceBookings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCapacity() {
		return this.capacity;
	}

	public void setCapacity(Integer capacity) {
		this.capacity = capacity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public Set getServiceBookings() {
		return this.serviceBookings;
	}

	public void setServiceBookings(Set serviceBookings) {
		this.serviceBookings = serviceBookings;
	}

}
