package com.markkryzh.hotel_software_tool.model;
// Generated 25 лист. 2016 3:50:37 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private int id;
	private String email;
	private String password;
	private String phone;
	private String name;
	private String surname;
	private String role;
	private short enabled;
	private Set roomBookings = new HashSet(0);
	private Set serviceBookings = new HashSet(0);

	public User() {
	}

	public User(int id, String email, String password, String phone, String name, String surname, String role,
			short enabled) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.name = name;
		this.surname = surname;
		this.role = role;
		this.enabled = enabled;
	}

	public User(int id, String email, String password, String phone, String name, String surname, String role,
			short enabled, Set roomBookings, Set serviceBookings) {
		this.id = id;
		this.email = email;
		this.password = password;
		this.phone = phone;
		this.name = name;
		this.surname = surname;
		this.role = role;
		this.enabled = enabled;
		this.roomBookings = roomBookings;
		this.serviceBookings = serviceBookings;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public short getEnabled() {
		return this.enabled;
	}

	public void setEnabled(short enabled) {
		this.enabled = enabled;
	}

	public Set getRoomBookings() {
		return this.roomBookings;
	}

	public void setRoomBookings(Set roomBookings) {
		this.roomBookings = roomBookings;
	}

	public Set getServiceBookings() {
		return this.serviceBookings;
	}

	public void setServiceBookings(Set serviceBookings) {
		this.serviceBookings = serviceBookings;
	}

}
